The purpose of software engineering is to control complexity, not to create it.
—Pamela Zave

In many cases, OOP seems to be particularly
suited for financial modeling and implementing financial algorithms.

| Term | Definition | Example |
|------|------------|---------|
| Class | An abstract definition of a certain type of objects | Human being |
| Object | An instance of a class | Sandra |
| Attribute | A feature of the class (class attribute) or of an instance of the class | Being a mammal, being male/female, color of eyes |
| Method | An operation that the class or an instance of the class can implement | Walking |
| Parameters | Input taken by a method to influence its behavior | Three steps |
| Instantiation | The process of creating a specific object based on an abstract class | Creating a specific human instance |


In [2]:
class HumanBeing(object):
    def __init__(self, first_name, eye_color):
        self.first_name = first_name
        self.eye_color = eye_color
        self.position = 0
    def walk_steps(self, steps):
        self.position += steps

In [11]:
dhairya = HumanBeing('dhairya', 'brown')

In [13]:
print(dhairya.first_name)
print(dhairya.position)
dhairya.walk_steps(10)
print(dhairya.position)

dhairya
0
10


# A Look at Python Objects

Let’s start by taking a brief look at some standard objects encountered in previous
chapters through the eyes of an OOP programmer.

## int

In [17]:
n = 5
print(type(n))
print(n.numerator)
print(n.bit_length())
print(n.__sizeof__())

<class 'int'>
5
3
28


## list

In [19]:
l = [2*i for i in range(10)]
print(type(l))
print(l[0])
l.append(20)
print(sum(l))
print(l.__sizeof__())
print(l)

<class 'list'>
0
110
168
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


## ndarray

int and list objects are standard Python objects. The NumPy ndarray object is a
“custom-made” object from an open source package.

In [21]:
import numpy as np
a = np.arange(16).reshape(4, 4)
print(a)
print(type(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
<class 'numpy.ndarray'>


In [23]:
print(a.nbytes)
print(a.sum())
print(a.cumsum(axis=0))
print(a.__sizeof__())

128
120
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]
 [24 28 32 36]]
128


## DataFrame

In [24]:
import pandas as pd
df = pd.DataFrame(a, columns=list('abcd'))
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [25]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [26]:
df.columns

Index(['a', 'b', 'c', 'd'], dtype='object')

In [27]:
df.sum()

a    24
b    28
c    32
d    36
dtype: int64

In [28]:
df.cumsum()

a   b   c   d
0   0   1   2   3
1   4   6   8  10
2  12  15  18  21
3  24  28  32  36

# Basics of Python Classes

This section covers major concepts and the concrete syntax to make use of OOP in
Python. The context now is about building custom classes to model types of objects
that cannot be easily, efficiently, or properly modeled by existing Python object types.
Throughout, the example of a financial instrument is used.

In [29]:
class FinancialInstrument(object):
    pass

In [30]:
fi = FinancialInstrument()
type(fi)

__main__.FinancialInstrument

In [31]:
fi.__str__()

'<__main__.FinancialInstrument object at 0x164e3aae0>'

In [33]:
fi.price = 100
fi.price

100

An important special method is __init__, which gets called during every instantiation of an object. It takes as parameters the object itself (self, by convention) and
potentially multiple others.

In [34]:
class FinancialInstrument(object):
    author = 'Dhairya Kantawala'
    def __init__(self, symbol, price):
        self.symbol = symbol
        self.price = price

In [35]:
FinancialInstrument.author

'Dhairya Kantawala'

In [36]:
aapl = FinancialInstrument('AAPL', 100)

In [37]:
aapl.symbol

'AAPL'

In [38]:
aapl.author

'Dhairya Kantawala'

In [39]:
aapl.price = 105
aapl.price

105

Prices of financial instruments change regularly, but the symbol of a financial instrument probably does not change. To introduce encapsulation to the class definition,
two methods, get_price() and set_price(), might be defined. The code that follows additionally inherits from the previous class definition (and not from object
anymore).

In [40]:
class FinancialInstrument(FinancialInstrument):
    def get_price(self):
        return self.price
    def set_price(self, price):
        self.price = price

In [41]:
fi = FinancialInstrument('AAPL', 100)

In [46]:
fi.get_price()

100

In [49]:
fi.set_price(120)
print(fi.get_price())
print(fi.price)

120
120


Encapsulation generally has the goal of hiding data from the user working with a
class. Adding getter and setter methods is one part of achieving this goal. However,
this does not prevent the user from directly accessing and manipulating instance
attributes. This is where private instance attributes come into play. They are defined
by two leading underscores.

In [50]:
class FinancialInstrument(object):
    def __init__(self, symbol, price):
        self.symbol = symbol
        self.__price = price

    def get_price(self):
        return self.__price

    def set_price(self, price):
        self.__price = price

In [52]:
fi = FinancialInstrument('AAPL', 100)
fi.get_price()

100

In [53]:
fi.__price

AttributeError: 'FinancialInstrument' object has no attribute '__price'

In [55]:
fi._FinancialInstrument__price

100

Consider another class that models a portfolio position of a financial instrument.
With the two classes aggregation as a concept is easily illustrated. An instance of the
PortfolioPosition class takes an instance of the FinancialInstrument class as an
attribute value. Adding an instance attribute, such as position_size, one can then
calculate, for instance, the position value.

In [58]:
class PortfolioPosition(object):
    def __init__(self, financial_instrument, position_size):
        self.position = financial_instrument
        self.__position_size = position_size
    def get_position_size(self):
        return self.__position_size
    def update_positon_size(self, position_size):
        self.__position_size = position_size
    def get_position_value(self):
        return self.__position_size * self.position.get_price()

In [59]:
pp = PortfolioPosition(fi, 10)
pp.get_position_size()

10

In [60]:
pp.get_position_value()

1000

In [61]:
pp.position.get_price()

100

In [62]:
pp.position.set_price(105)
pp.get_position_value()

1050

# Python Data Model

In [63]:
class Vector(object):
    def __init__(self, x=0, y=0, z=0):
        self.x = x
        self.y = y
        self.z = z

In [65]:
v = Vector(1, 2, 3)
v

The special method __repr__ allows the definition of custom string representations.

In [68]:
class Vector(Vector):
    def __repr__(self):
        return 'Vector(%r, %r, %r)'%(self.x, self.y, self.z)

In [69]:
v = Vector(1, 2, 3)
v

Vector(1, 2, 3)

In [70]:
print(v)

Vector(1, 2, 3)


abs() and bool() are two standard Python functions whose behavior on the Vector
class can be defined via the special methods __abs__ and __bool__.

In [75]:
class Vector(Vector):
    def __abs__(self):
        return ((self.x ** 2 + self.y** 2 + self.z**2)**0.5)
    def __bool__(self):
        return bool(abs(self))

In [76]:
v = Vector(1, 2, -1)
abs(v)

2.449489742783178

In [77]:
bool(v)

True

In [78]:
v = Vector(0,0,0)
bool(v)

False

As shown multiple times, the + and * operators can be applied to almost any Python
object. The behavior is defined through the special methods __add__ and __mul__.

In [79]:
class Vector(Vector):
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x, y, z)
    def __mul__(self, scalar):
        return Vector(self.x*scalar, self.y*scalar, self.z*scalar)

In [81]:
v = Vector(1, 2, 3)
v + Vector(2, 3, 4)

Vector(3, 5, 7)

In [82]:
v * 2

Vector(2, 4, 6)

Another standard Python function is len(), which gives the length of an object in
number of elements. This function accesses the special method __len__ when called
on an object. On the other hand, the special method __getitem__ makes indexing via
the square bracket notation possible.

In [83]:
class Vector(Vector):
    def __len__(self):
        return 3
    def __getitem__(self, i):
        if i in[0, -3]: return self.x
        elif i in [1, -2]: return self.y
        elif i in [2, -1]: return self.z
        else: raise IndexError('Index out of range.')

In [84]:
v = Vector(1, 2, 3)

In [86]:
len(v)

3

In [87]:
v[0]

1

In [88]:
v[-2]

2

In [91]:
v[3]

IndexError: Index out of range.

Finally, the special method __iter__ defines the behavior during iterations over elements of an object. An object for which this operation is defined is called iterable. For
instance, all collections and containers are iterable.

In [92]:
class Vector(Vector):
    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

In [93]:
v = Vector(-10, 3, 7)
for coord in v:
    print(coord)

-10
3
7
